services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_HEAP_OPTS: "-Xmx128M -Xms128M"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:

      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"

  init-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: init-kafka
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      # Block until kafka is reachable
      echo -e 'Waiting for Kafka to be ready...'
      cub kafka-ready -b kafka:9092 1 40
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic questions-socius --replication-factor 1 --partitions 10
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic questions-private --replication-factor 1 --partitions 10
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic questions-oakhillpines --replication-factor 1 --partitions 10
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic answers --replication-factor 1 --partitions 10
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list

  answer-consumer:
    build: .
    container_name: answer-consumer
    command: python answer_consumer.py
    depends_on:
      - kafka
      - postgres-private
      - postgres-socius
      - postgres-oakhillpines
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_PRIVATE: postgres-private
      POSTGRES_HOST_SOCIUS: postgres-socius
      POSTGRES_HOST_OAKHILLPINES: postgres-oakhillpines
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  postgres-private:
    image: postgres:15
    container_name: postgres-private
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_private_data:/var/lib/postgresql/data

  postgres-socius:
    image: postgres:15
    container_name: postgres-socius
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_socius_data:/var/lib/postgresql/data

  postgres-oakhillpines:
    image: postgres:15
    container_name: postgres-oakhillpines
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_oakhillpines_data:/var/lib/postgresql/data

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

  oakhillpines-api:
    build: .
    container_name: oakhillpines-api
    expose:
      - "8000"
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS_PUBLIC}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres-oakhillpines
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DEFAULT_MODEL=${DEFAULT_MODEL_OAKHILLPINES}
    depends_on:
      - postgres-oakhillpines
    command: gunicorn oakhillpines_api:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  private-api:
    build: .
    container_name: private-api
    expose:
      - "8001"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres-private
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_PRIVATE}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS_PRIVATE}
      - DEFAULT_MODEL=${DEFAULT_MODEL_PRIVATE}
    depends_on:
      - postgres-private
    command: gunicorn private_api:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001

  socius-api:
    build: .
    container_name: socius-api
    expose:
      - "8002"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres-socius
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_SOCIUS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS_PRIVATE}
      - DEFAULT_MODEL=${DEFAULT_MODEL_SOCIUS}
    depends_on:
      - postgres-socius
    command: gunicorn socius_api:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8002

volumes:
  postgres_private_data:
  postgres_socius_data:
  postgres_oakhillpines_data:
